version: "3.9"

services:
    backend:
        build:
            context: backend
        ports: 
          - '8000:8000'
        container_name: SAFlightAPI
    frontend:
        stdin_open: true
        build:
            context: frontend
        volumes:
            - /app/node_modules
            - ./frontend/src:/app/src
        ports:
            - '3000:3000'
        container_name: SAFlightSPA
        
