# Generated by Django 3.2.12 on 2022-04-19 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('icao', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao_code', models.CharField(blank=True, max_length=25, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('latitude_deg', models.FloatField(blank=True, null=True)),
                ('longitude_deg', models.FloatField(blank=True, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(blank=True, max_length=250, null=True)),
                ('gate', models.CharField(blank=True, max_length=250, null=True)),
                ('baggage', models.CharField(blank=True, max_length=250, null=True)),
                ('time_delay', models.IntegerField(blank=True, null=True)),
                ('time_scheduled', models.TimeField(blank=True, null=True)),
                ('time_estimated', models.TimeField(blank=True, null=True)),
                ('time_actual', models.TimeField(blank=True, null=True)),
                ('estimated_runway', models.CharField(blank=True, max_length=250, null=True)),
                ('actual_runway', models.CharField(blank=True, max_length=250, null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saflightsapi.airport')),
            ],
            options={
                'ordering': ['time_scheduled'],
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal', models.CharField(blank=True, max_length=250, null=True)),
                ('gate', models.CharField(blank=True, max_length=250, null=True)),
                ('baggage', models.CharField(blank=True, max_length=250, null=True)),
                ('time_delay', models.IntegerField(blank=True, null=True)),
                ('time_scheduled', models.TimeField(blank=True, null=True)),
                ('time_estimated', models.TimeField(blank=True, null=True)),
                ('time_actual', models.TimeField(blank=True, null=True)),
                ('estimated_runway', models.CharField(blank=True, max_length=250, null=True)),
                ('actual_runway', models.CharField(blank=True, max_length=250, null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saflightsapi.airport')),
            ],
            options={
                'ordering': ['time_scheduled'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('iata_code', models.CharField(blank=True, max_length=20, null=True)),
                ('icao_code', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('airline', models.CharField(blank=True, max_length=250, null=True)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saflightsapi.arrival')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saflightsapi.departure')),
            ],
        ),
    ]
