# Generated by Django 3.2.12 on 2022-04-13 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('icao_code', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('iata_code', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=250)),
                ('municipality', models.CharField(max_length=250)),
                ('latitude_deg', models.FloatField(blank=True, null=True)),
                ('longitude_deg', models.FloatField(blank=True, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DEPARTURE', 'departure'), ('ARRIVAL', 'arrival')], max_length=10)),
                ('terminal', models.CharField(blank=True, max_length=250, null=True)),
                ('gate', models.CharField(blank=True, max_length=250, null=True)),
                ('baggage', models.CharField(blank=True, max_length=250, null=True)),
                ('time_delay', models.IntegerField(blank=True, null=True)),
                ('time_scheduled', models.TimeField(blank=True, null=True)),
                ('time_estimated', models.TimeField(blank=True, null=True)),
                ('time_actual', models.TimeField(blank=True, null=True)),
                ('estimated_runway', models.CharField(blank=True, max_length=250, null=True)),
                ('actual_runway', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('iata_code', models.CharField(blank=True, max_length=20, null=True)),
                ('icao_code', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('airline', models.CharField(blank=True, max_length=250, null=True)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_flight_set', to='saflightsapi.flightdetail')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_flight_set', to='saflightsapi.flightdetail')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport_set', to='saflightsapi.airport')),
                ('source_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport_set', to='saflightsapi.airport')),
            ],
        ),
    ]
