# Generated by Django 3.2.12 on 2022-04-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata_code', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('municipality', models.CharField(max_length=250)),
                ('latitude_deg', models.FloatField(blank=True, null=True)),
                ('longitude_deg', models.FloatField(blank=True, null=True)),
                ('elevation', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(blank=True, max_length=20)),
                ('airline', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FlightDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('DEPARTURE', 'departure'), ('ARRIVAL', 'arrival')], max_length=10)),
                ('airport', models.CharField(max_length=250)),
                ('iata', models.CharField(max_length=10)),
                ('icao', models.CharField(max_length=10)),
                ('terminal', models.CharField(max_length=250)),
                ('gate', models.CharField(max_length=250)),
                ('baggage', models.CharField(max_length=250)),
                ('time_delay', models.TimeField(blank=True, null=True)),
                ('time_scheduled', models.TimeField(blank=True, null=True)),
                ('time_estimated', models.TimeField(blank=True, null=True)),
                ('time_actual', models.TimeField(blank=True, null=True)),
                ('estimated_runway', models.CharField(blank=True, max_length=250, null=True)),
                ('actual_runway', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
