# Generated by Django 3.2.12 on 2022-04-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saflightsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
